name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'corretto'

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Test
      run: ./gradlew test --no-daemon

    - name: Package JAR
      run: ./gradlew bootJar --no-daemon

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: build/libs/*.jar
